export type TransactionType =
  | "Income"
  | "Expense"
  | "Debt (I owe)"
  | "Loan (Owed to me)";

export type CategoryType =
  | "Business & Content"
  | "Education"
  | "Fixed Subscriptions"
  | "Lifestyle"
  | "Salary / Income"
  | "Freelance"
  | "Allowance"
  | "Loans & Debts"
  | "Beauty & Health"
  | "Food Expenses"
  | "Transportation"
  | "Miscellaneous"
  | "Other";

export type Transaction = {
  id: number;
  date: string;
  item: string;
  cost: number;
  type: TransactionType;
  status: "Paid" | "Pending";
  category: CategoryType;
  mop: string;
};

export const initialData: Transaction[] = [
  // Monthly tracking base
  {
    id: 101,
    date: "2026-05-01",
    item: "Monthly Allowance",
    cost: 15000,
    type: "Income",
    status: "Paid",
    category: "Allowance",
    mop: "G-CASH",
  },
  {
    id: 102,
    date: "2026-05-05",
    item: "Freelance Project",
    cost: 5000,
    type: "Income",
    status: "Paid",
    category: "Freelance",
    mop: "Go-Tyme",
  },

  // Drive (April)
  {
    id: 1001,
    date: "2026-04-12",
    item: "Google Drive",
    cost: 119,
    type: "Expense",
    status: "Paid",
    category: "Fixed Subscriptions",
    mop: "G-Cash",
  },
  {
    id: 1002,
    date: "2026-04-26",
    item: "Google Drive (Pending)",
    cost: 119,
    type: "Expense",
    status: "Pending",
    category: "Fixed Subscriptions",
    mop: "-",
  },

  // Drive (May)
  {
    id: 2003,
    date: "2026-05-10",
    item: "Google Drive",
    cost: 10,
    type: "Expense",
    status: "Paid",
    category: "Fixed Subscriptions",
    mop: "G-Cash",
  },

  // Spotify
  {
    id: 1003,
    date: "2026-05-27",
    item: "Spotify (Pending)",
    cost: 157,
    type: "Expense",
    status: "Pending",
    category: "Fixed Subscriptions",
    mop: "-",
  },
  {
    id: 2004,
    date: "2026-05-15",
    item: "Spotify",
    cost: 99,
    type: "Expense",
    status: "Paid",
    category: "Fixed Subscriptions",
    mop: "G-Cash",
  },

  // TikTok Boost (April)
  {
    id: 1004,
    date: "2026-04-12",
    item: "TikTok Boost",
    cost: 35.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1005,
    date: "2026-04-13",
    item: "TikTok Boost",
    cost: 35.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1006,
    date: "2026-04-14",
    item: "TikTok Boost",
    cost: 35.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1007,
    date: "2026-04-15",
    item: "TikTok Boost",
    cost: 35.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1008,
    date: "2026-04-16",
    item: "TikTok Boost",
    cost: 35.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1009,
    date: "2026-04-17",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1010,
    date: "2026-04-19",
    item: "TikTok Boost",
    cost: 35.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1011,
    date: "2026-04-20",
    item: "TikTok Boost",
    cost: 35.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1012,
    date: "2026-04-21",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1013,
    date: "2026-04-22",
    item: "TikTok Boost",
    cost: 66.0,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1014,
    date: "2026-04-23",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1015,
    date: "2026-04-24",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1016,
    date: "2026-04-25",
    item: "TikTok Boost",
    cost: 35.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1017,
    date: "2026-04-26",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1018,
    date: "2026-04-27",
    item: "TikTok Boost",
    cost: 35.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1019,
    date: "2026-04-28",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1020,
    date: "2026-04-29",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 1021,
    date: "2026-04-30",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },

  // TikTok Boost (May)
  {
    id: 2005,
    date: "2026-05-01",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2006,
    date: "2026-05-02",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2007,
    date: "2026-05-03",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2008,
    date: "2026-05-04",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2009,
    date: "2026-05-05",
    item: "TikTok Boost",
    cost: 71.42,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2010,
    date: "2026-05-06",
    item: "TikTok Boost",
    cost: 147.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2011,
    date: "2026-05-08",
    item: "TikTok Boost",
    cost: 84,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2012,
    date: "2026-05-09",
    item: "TikTok Boost",
    cost: 147.71,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2013,
    date: "2026-05-10",
    item: "TikTok Boost",
    cost: 84,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2014,
    date: "2026-05-11",
    item: "TikTok Boost",
    cost: 84,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },
  {
    id: 2015,
    date: "2026-05-16",
    item: "TikTok Boost",
    cost: 134.0,
    type: "Expense",
    status: "Paid",
    category: "Business & Content",
    mop: "G-Cash",
  },

  // Dental
  {
    id: 2016,
    date: "2026-05-04",
    item: "Dental",
    cost: 1700,
    type: "Expense",
    status: "Paid",
    category: "Beauty & Health",
    mop: "G-Cash",
  },

  // Food (April)
  {
    id: 1022,
    date: "2026-04-15",
    item: "The Portal Food",
    cost: 245.0,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 1023,
    date: "2026-04-15",
    item: "Takoyaki Half",
    cost: 64.0,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 1024,
    date: "2026-04-15",
    item: "Mega Fries w/ Silly Poco",
    cost: 291.0,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Cash",
  },

  // Food (May)
  {
    id: 2017,
    date: "2026-05-01",
    item: "Fries w/poco",
    cost: 298,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Cash",
  },
  {
    id: 2018,
    date: "2026-05-01",
    item: "Facemask - NBS",
    cost: 114,
    type: "Expense",
    status: "Paid",
    category: "Miscellaneous",
    mop: "Maribank",
  },
  {
    id: 2019,
    date: "2026-05-01",
    item: "BJ Fruitas",
    cost: 85,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2020,
    date: "2026-05-02",
    item: "Fries w/poco GF",
    cost: 315,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Maribank",
  },
  {
    id: 2021,
    date: "2026-05-02",
    item: "Mogu-Mogu 7-Eleven",
    cost: 50,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2022,
    date: "2026-05-03",
    item: "Food CTK",
    cost: 100,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2023,
    date: "2026-05-04",
    item: "SB",
    cost: 185,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2024,
    date: "2026-05-04",
    item: "SB",
    cost: 195,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2025,
    date: "2026-05-04",
    item: "Poco Fame",
    cost: 149,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Maribank",
  },
  {
    id: 2026,
    date: "2026-05-05",
    item: "Watsons - Pads",
    cost: 190,
    type: "Expense",
    status: "Paid",
    category: "Beauty & Health",
    mop: "Maribank",
  },
  {
    id: 2027,
    date: "2026-05-06",
    item: "Banana n Mogu 7/11",
    cost: 73,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2028,
    date: "2026-05-06",
    item: "Avocado Fluffy",
    cost: 299,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Cash",
  },
  {
    id: 2029,
    date: "2026-05-07",
    item: "SB",
    cost: 200,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2030,
    date: "2026-05-07",
    item: "Boulangerie",
    cost: 69,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2031,
    date: "2026-05-08",
    item: "FoodPanda - Empanada",
    cost: 202.3,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2032,
    date: "2026-05-09",
    item: "SB",
    cost: 200,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Cash",
  },
  {
    id: 2033,
    date: "2026-05-09",
    item: "Dunkin Donuts",
    cost: 100,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Cash",
  },
  {
    id: 2034,
    date: "2026-05-10",
    item: "Food CTK",
    cost: 50,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Cash",
  },
  {
    id: 2035,
    date: "2026-05-10",
    item: "Ice Cream 7/11",
    cost: 195,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "G-Cash",
  },
  {
    id: 2036,
    date: "2026-05-12",
    item: "Bos Coffee",
    cost: 185,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Go Tyme",
  },
  {
    id: 2037,
    date: "2026-05-12",
    item: "Dunkin Donut",
    cost: 100,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Cash",
  },
  {
    id: 2038,
    date: "2026-05-15",
    item: "Street Food",
    cost: 120,
    type: "Expense",
    status: "Paid",
    category: "Food Expenses",
    mop: "Cash",
  },
  {
    id: 2039,
    date: "2026-05-15",
    item: "Mr. Quickie",
    cost: 190,
    type: "Expense",
    status: "Paid",
    category: "Miscellaneous",
    mop: "Cash",
  },
  {
    id: 2040,
    date: "2026-05-15",
    item: "Fuji Film",
    cost: 175,
    type: "Expense",
    status: "Paid",
    category: "Miscellaneous",
    mop: "Go Tyme",
  },
  {
    id: 2041,
    date: "2026-05-15",
    item: "Parking Fee (Tita)",
    cost: 50,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "Go Tyme",
  },

  // Transpo (May)
  {
    id: 2042,
    date: "2026-05-04",
    item: "P2P Dental",
    cost: 109,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "G-Cash",
  },
  {
    id: 2043,
    date: "2026-05-04",
    item: "Transpo (total)",
    cost: 115,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "G-Cash",
  },
  {
    id: 2044,
    date: "2026-05-06",
    item: "C. Xian to Paragon",
    cost: 135,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "G-Cash",
  },
  {
    id: 2045,
    date: "2026-05-09",
    item: "SB Portal to SM light",
    cost: 50,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "G-Cash",
  },
  {
    id: 2046,
    date: "2026-05-10",
    item: "Paragon n EFS",
    cost: 96,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "-",
  },
  {
    id: 2047,
    date: "2026-05-15",
    item: "Paragon n Sm MegaMall",
    cost: 50,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "G-Cash",
  },
  {
    id: 2048,
    date: "2026-05-15",
    item: "Sm MegaMall n Paragon",
    cost: 85,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "Go Tyme",
  },
  {
    id: 2049,
    date: "2026-05-06",
    item: "PUP n Paragon",
    cost: 106,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "Cash",
  },
  {
    id: 2050,
    date: "2026-05-06",
    item: "Paragon n Pup",
    cost: 96,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "Go Tyme",
  },
  {
    id: 2051,
    date: "2026-05-06",
    item: "Pup n Paragon (Jeep)",
    cost: 15,
    type: "Expense",
    status: "Paid",
    category: "Transportation",
    mop: "Cash",
  },

  // PUP / School
  {
    id: 2052,
    date: "2026-05-06",
    item: "PONDO",
    cost: 500,
    type: "Expense",
    status: "Paid",
    category: "Education",
    mop: "Cash",
  },
  {
    id: 2053,
    date: "2026-05-08",
    item: "PUP School",
    cost: 4000,
    type: "Expense",
    status: "Pending",
    category: "Education",
    mop: "-",
  },
  {
    id: 2054,
    date: "2026-05-08",
    item: "Statistician",
    cost: 3200,
    type: "Expense",
    status: "Paid",
    category: "Education",
    mop: "Go-Tyme",
  },

  // Subscriptions notes
  {
    id: 3001,
    date: "2026-05-30",
    item: "Meta Verified fb [CANCEL]",
    cost: 0,
    type: "Expense",
    status: "Pending",
    category: "Fixed Subscriptions",
    mop: "-",
  },
  {
    id: 3002,
    date: "2026-05-30",
    item: "Meta Verified ig [CANCEL]",
    cost: 0,
    type: "Expense",
    status: "Pending",
    category: "Fixed Subscriptions",
    mop: "-",
  },
];
